# Generated by Django 3.2.6 on 2021-08-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmdb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=255),
        ),
    ]
