# Generated by Django 3.2.6 on 2021-08-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmdb_app', '0004_auto_20210813_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='movie',
            field=models.ManyToManyField(related_name='genres', to='kmdb_app.Movie'),
        ),
    ]
