# Generated by Django 3.2.6 on 2021-08-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmdb_app', '0005_alter_genre_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='kmdb_app.Genre'),
        ),
    ]
