# Generated by Django 3.2.6 on 2021-08-13 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kmdb_app', '0006_auto_20210813_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='critic',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_movie', to='kmdb_app.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
