# Generated by Django 3.2.6 on 2021-08-15 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kmdb_app', '0010_alter_review_critic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='critic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_critic', to=settings.AUTH_USER_MODEL),
        ),
    ]
